#!/bin/bash

sudo apt-get update >/dev/null 2>&1
sudo apt-get install -y python3 python3-pip >/dev/null

# proj dir
homedir=/home/one_click_cloud_dir
sudo mkdir -p $homedir
cd $homedir

# sources
wget 


# dependencies
sudo pip3 install -q -r requirements.txt

server_ip=$(curl -s ifconfig.me)
sed -i "s/127.0.0.1/$server_ip/" ./one_click_cloud/api.py

# gunicorn
# log
sudo mkdir -p /var/log/gunicorn
# service
pdir=$(pwd)
cat << EOF > tmp
[Unit]
Description=one_click_cloud
After=network.target

[Service]
User=$(whoami)
Group=$(groups)
WorkingDirectory=$pdir
Environment="PYTHONPATH=$pdir"
ExecStart=gunicorn -c gunicorn_conf.py one_click_cloud.api:app
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
sudo mv tmp /etc/systemd/system/one_click_cloud.service
sudo systemctl daemon-reload
sudo systemctl enable one_click_cloud.service
sudo systemctl restart one_click_cloud.service

# logrotate
# separate logfile
cat <<EOF > tmp
/var/log/gunicorn/*.log {
    daily
    dateext
    dateformat -%Y-%m-%d
    dateyesterday
    rotate 30
    missingok
    notifempty
}
EOF
sudo mv tmp /etc/logrotate.d/gunicorn
sudo logrotate /etc/logrotate.d/gunicorn
