#!/bin/bash

echo "update and install"
sudo apt-get update >/dev/null 2>&1
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip >/dev/null

echo "create project dir"
homeDir=/home/one_click_server
sudo rm -rf $homeDir && sudo mkdir -p $homeDir
cd $homeDir

echo "download sources"
wget -q https://raw.githubusercontent.com/minximenes/renrengpt/main/server/requirements.txt
wget -q https://raw.githubusercontent.com/minximenes/renrengpt/main/server/gunicorn_conf.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/__init__.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/api.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/auth.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/openClient.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/wrapper.py

echo "install dependencies"
sudo pip3 install -q -r requirements.txt

echo "configurate gunicorn"
# log
gunicornLogDir=/var/log/gunicorn
sudo mkdir -p $gunicornLogDir
# service
pdir=$(pwd)
cat << EOF > tmp
[Unit]
Description=one_click_cloud
After=network.target

[Service]
User=$(whoami)
Group=$(groups)
WorkingDirectory=$pdir
Environment="PYTHONPATH=$pdir"
ExecStart=gunicorn -c gunicorn_conf.py one_click_cloud.api:app
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
sudo mv tmp /etc/systemd/system/one_click_cloud.service
sudo systemctl daemon-reload
sudo systemctl enable one_click_cloud.service
sudo systemctl restart one_click_cloud.service
sudo systemctl status one_click_cloud.service

echo "configurate logrotate"
# log
cat <<EOF > tmp
$gunicornLogDir/*.log {
    daily
    dateext
    dateformat -%Y-%m-%d
    dateyesterday
    rotate 30
    missingok
    notifempty
}
EOF
sudo mv tmp /etc/logrotate.d/gunicorn
sudo logrotate /etc/logrotate.d/gunicorn

echo "create userdata dir"
dataDir=/home/one_click_data
sudo mkdir -p $dataDir
cd $dataDir
wget -q https://raw.githubusercontent.com/minximenes/renrengpt/main/data/LTAI5t7LSJCM1dCUszcqCHH4 -O LTAI5t7LSJCM1dCUszcqCHH4

echo "end"