#!/bin/bash

# wget https://raw.githubusercontent.com/minximenes/renrengpt/main/server/deploy
# sudo bash deploy

sudo apt-get update >/dev/null 2>&1
sudo apt-get install -y python3 python3-pip >/dev/null

# proj dir
homeDir=/home/one_click_cloud_dir
sudo rm -rf $homeDir && sudo mkdir -p $homeDir
cd $homeDir

# sources
wget https://raw.githubusercontent.com/minximenes/renrengpt/main/server/requirements.txt
wget https://raw.githubusercontent.com/minximenes/renrengpt/main/server/gunicorn_conf.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/__init__.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/api.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/auth.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/openClient.py
wget -q -P ./one_click_cloud https://raw.githubusercontent.com/minximenes/renrengpt/main/server/one_click_cloud/wrapper.py

# dependencies
sudo pip3 install -q -r requirements.txt

# gunicorn
# log
gunicornLogDir=/var/log/gunicorn
sudo rm -rf $gunicornLogDir && sudo mkdir -p $gunicornLogDir
# service
pdir=$(pwd)
cat << EOF > tmp
[Unit]
Description=one_click_cloud
After=network.target

[Service]
User=$(whoami)
Group=$(groups)
WorkingDirectory=$pdir
Environment="PYTHONPATH=$pdir"
ExecStart=gunicorn -c gunicorn_conf.py one_click_cloud.api:app
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
sudo mv tmp /etc/systemd/system/one_click_cloud.service
sudo systemctl daemon-reload
sudo systemctl enable one_click_cloud.service
sudo systemctl restart one_click_cloud.service

# logrotate
# separate logfile
cat <<EOF > tmp
/var/log/gunicorn/*.log {
    daily
    dateext
    dateformat -%Y-%m-%d
    dateyesterday
    rotate 30
    missingok
    notifempty
}
EOF
sudo mv tmp /etc/logrotate.d/gunicorn
sudo logrotate /etc/logrotate.d/gunicorn
